/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.practica3;

import java.util.ArrayList;
import javax.swing.JButton;
import controlador.Controlador3;
import modelo.Carta;
import modelo.utilidades.Conversor;

/**
 *
 * @author hectorius
 */
@SuppressWarnings("serial")
public class VistaBoard extends javax.swing.JFrame {
	private String CARTABOARD="Pulsa en una carta de la mesa";
	private String RUTA = "src/ImagenCartas/";
	private BoardPanel2 boardPanel;
    /**
     * Creates new form VistaBoard
     */
    public VistaBoard() {
    	try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	cartasUsadas = new ArrayList<String>();
    	conversor = new Conversor();
    	boardPanel = new BoardPanel2(CARTABOARD);
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        RandButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jug=0;
        pos=0;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(RUTA + "NoCard.png")); // NOI18N
        RandButton.setText("Random");
    

        jTextField1.setText("0%");
        jTextField2.setText("0%");
        jTextField3.setText("0%");
        jTextField4.setText("0%");
        jTextField5.setText("0%");
        jTextField6.setText("0%");
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(931, 931, 931)
                    .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 179, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton17)
                .addGap(406, 406, 406))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(349, 349, 349))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(184, 184, 184)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton12)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(111, 111, 111)
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8)
                                    .addComponent(jButton6)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(RandButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addComponent(jButton6))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton16)
                            .addComponent(jButton17)
                            .addComponent(jButton15)
                            .addComponent(jButton14)
                            .addComponent(jButton13))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RandButton))
                                    .addComponent(jButton7)
                                    .addComponent(jButton11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(jButton10))
                                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(126, 448, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }
    
    public void addCartaJugador (int jugador, int cartaPosicion){
    	//Si la carta no se ha colocado, se coloca
    	if (!existeCarta(this.cartaAColocar)){
		int colocarCartaUsada = (jugador*2)+cartaPosicion;
		String nombreFichero = this.conversor.cartaParaFichero(this.cartaAColocar);
		String imagenCarta = RUTA + nombreFichero + ".png";
		//Metemos la carta en la posicion que corresponde
		this.cartasUsadas.add(this.cartaAColocar.toString());
		
		switch(colocarCartaUsada){//Vamos a poner en el boton correspondiente la imagen
    		case 0: this.jButton1.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 1: this.jButton2.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 2: this.jButton3.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 3: this.jButton4.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 4: this.jButton5.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 5: this.jButton6.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 6: this.jButton7.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 7: this.jButton8.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 8: this.jButton9.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 9: this.jButton10.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 10: this.jButton11.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 11: this.jButton12.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 12: this.jButton13.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 13: this.jButton14.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 14: this.jButton15.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 15: this.jButton16.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 16: this.jButton17.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		default: break;
		}
    	jug+=pos;
    	pos^=1;
    	}
    }

    public void addCartaMesa(int pos) {
    	//Si la carta no se ha colocado, se coloca
    	if (!existeCarta(this.cartaAColocar)){
		String nombreFichero = this.conversor.cartaParaFichero(this.cartaAColocar);
		String imagenCarta = RUTA + nombreFichero + ".png";
		//Metemos la carta en la posicion que corresponde
		this.cartasUsadas.add(this.cartaAColocar.toString());
		
		switch(pos){//Vamos a poner en el boton correspondiente la imagen
    		case 0: this.jButton13.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 1: this.jButton14.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 2: this.jButton15.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 3: this.jButton16.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		case 4: this.jButton17.setIcon(new javax.swing.ImageIcon(imagenCarta)); break;
    		default: break;
		}
    	}
	}
    
	public void arranca() {
		setLocationRelativeTo(null);//centra la ventana en la pantalla
		setVisible(true);//visualiza la ventana
	}
	public void setControlador(Controlador3 control) {
		  jButton1.addActionListener(control);
		  jButton1.setActionCommand("ChangeCard" + " 0 0");
		  jButton2.addActionListener(control);
		  jButton2.setActionCommand("ChangeCard" + " 0 1");
		  jButton3.addActionListener(control);
		  jButton3.setActionCommand("ChangeCard" + " 1 0");
		  jButton4.addActionListener(control);
		  jButton4.setActionCommand("ChangeCard" + " 1 1");
		  jButton5.addActionListener(control);
		  jButton5.setActionCommand("ChangeCard" + " 2 0");
		  jButton6.addActionListener(control);
		  jButton6.setActionCommand("ChangeCard" + " 2 1");
		  jButton7.addActionListener(control);
		  jButton7.setActionCommand("ChangeCard" + " 3 0");
		  jButton8.addActionListener(control);
		  jButton8.setActionCommand("ChangeCard" + " 3 1");
		  jButton9.addActionListener(control);
		  jButton9.setActionCommand("ChangeCard" + " 4 0");
		  jButton10.addActionListener(control);
		  jButton10.setActionCommand("ChangeCard" + " 4 1");
		  jButton11.addActionListener(control);
		  jButton11.setActionCommand("ChangeCard" + " 5 0");
		  jButton12.addActionListener(control);
		  jButton12.setActionCommand("ChangeCard" + " 5 1");
		  
		  jButton13.addActionListener(control);
		  jButton13.setActionCommand("CartaEnMesa" + " 0");
		  jButton14.addActionListener(control);
		  jButton14.setActionCommand("CartaEnMesa" + " 1");
		  jButton15.addActionListener(control);
		  jButton15.setActionCommand("CartaEnMesa" + " 2");
		  jButton16.addActionListener(control);
		  jButton16.setActionCommand("CartaEnMesa" + " 3");
		  jButton17.addActionListener(control);
		  jButton17.setActionCommand("CartaEnMesa" + " 4");
		  
		  
		  RandButton.addActionListener(control);
		  RandButton.setActionCommand("SelecCard Rand");
		  boardPanel.setControlador(control);
	}
	 
    private boolean existeCarta(Carta c){
    	boolean existe=false;
    	int i = 0;
    	while (!existe && i < this.cartasUsadas.size()){
    		if (c.toString().equals(this.cartasUsadas.get(i).toString())){
    			existe = true;
    		}
    		i++;
    	}
    	return existe;
    }
        
    public void setCartaSelec(Carta cartaSelec) {
		this.cartaAColocar = cartaSelec;
	}
    public void toggleBoard(JButton boton) {
    	Carta carta = new Carta(boton.getText());
    	if(existeCarta(carta)) return;
    	this.cartaAColocar = carta;

	}
    
    public void setEquities(int[] equities) {
		jTextField1.setText(String.valueOf(equities[0]));
		jTextField2.setText(String.valueOf(equities[1]));
		jTextField3.setText(String.valueOf(equities[2]));
		jTextField4.setText(String.valueOf(equities[3]));
		jTextField5.setText(String.valueOf(equities[4]));
		jTextField6.setText(String.valueOf(equities[5]));
	}

    private javax.swing.JButton RandButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private Carta cartaAColocar;
    private int jug, pos;
    private ArrayList<String> cartasUsadas;
    private Conversor conversor;
    // End of variables declaration//GEN-END:variables
}
