/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import controlador.controlador;

/**
 *
 * @author Jose Manuel
 */
@SuppressWarnings("serial")
public class VistaRangos extends JFrame implements InterfazVistaRangos{

    private JButton Generar;
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JTextField entradaTexto;
    private RangosPanel rangosPanel;
    private javax.swing.JTextField salidaMarcados;
    private javax.swing.JTextField porcentajeManos;
    private javax.swing.JButton calcularPorcentajeManos;
    private javax.swing.JSlider slideAzar;
  
    /**
     * Creates new form vistaRangos
     */
    public VistaRangos() {
    	 try {
             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 if ("Nimbus".equals(info.getName())) {
                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
                     break;
                 }
             }
         } catch (ClassNotFoundException ex) {
             java.util.logging.Logger.getLogger(VistaRangos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (InstantiationException ex) {
             java.util.logging.Logger.getLogger(VistaRangos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (IllegalAccessException ex) {
             java.util.logging.Logger.getLogger(VistaRangos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
             java.util.logging.Logger.getLogger(VistaRangos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	slideAzar = new javax.swing.JSlider();
        rangosPanel = new RangosPanel(RANGO);
        entradaTexto = new javax.swing.JTextField();
        botonSeleccionar = new javax.swing.JButton();
        salidaMarcados = new javax.swing.JTextField();
        Generar = new javax.swing.JButton();
        porcentajeManos = new javax.swing.JTextField();
        calcularPorcentajeManos = new javax.swing.JButton();
        
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        slideAzar.setValue(0);
        slideAzar.setDoubleBuffered(true);
        slideAzar.setFocusable(false);
        slideAzar.addChangeListener(new javax.swing.event.ChangeListener() {
			@Override
			public void stateChanged(ChangeEvent e) {
				mostrarPorcentajeRangos();
			}});
       
        botonSeleccionar.setText("Seleccionar");
        botonSeleccionar.setActionCommand(SELECCIONAR);
        porcentajeManos.setEditable(false);
        porcentajeManos.setFocusable(false);
        salidaMarcados.setEditable(false);
        salidaMarcados.setFocusable(false);
        calcularPorcentajeManos.setText("Calcular manos");
        calcularPorcentajeManos.setActionCommand(PORCENTAJE);
        Generar.setText("Generar");
        Generar.setActionCommand(GENERAR);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                	
                	.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                		.addComponent(slideAzar)
                		
                		.addComponent(porcentajeManos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                			)
                	.addComponent(rangosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(salidaMarcados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(entradaTexto, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonSeleccionar)
                            
                            .addGroup(layout.createSequentialGroup()
                            .addComponent(Generar)
                			.addGap(39, 39, 39)
                			
                			
                			.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                			.addComponent(calcularPorcentajeManos)
                			))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSeleccionar)
                	)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salidaMarcados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Generar)	
                	.addComponent(calcularPorcentajeManos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rangosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                		 .addComponent(porcentajeManos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(slideAzar)
                    	)
            	)
        );
    }// </editor-fold>//GEN-END:initComponents
    
      
    public void clean() {
    	rangosPanel.clean();
    }
    /*
     * Accion que realizan todos los JToggle
     * */
    public void toggle(JToggleButton boton) {
    	 rangosPanel.toggle(boton);
    }
    
    public void setControlador(controlador control) {
    	rangosPanel.setControlador(control);
    	botonSeleccionar.addActionListener(control);
        calcularPorcentajeManos.addActionListener(control);
        Generar.addActionListener(control);
	}

	public void arranca() {
		pack();// coloca los componentes
		setLocationRelativeTo(null);//centra la ventana en la pantalla
		setVisible(true);//visualiza la ventana
	}

	public boolean isSelected(int fila, int col) {
		return rangosPanel.isSelected(fila, col);
	}

	public void muestraRango(String s) {
		salidaMarcados.setText(s);
	}

	public String getRangoTexto() {
		return entradaTexto.getText();
	}

	public void pintaRango(int fila, int col) {
		rangosPanel.pintaRango(fila, col); 
	}

	public void mostrarPorcentajeRangos() {
		clean();
    	int porcentaje = this.slideAzar.getValue();
    	this.porcentajeManos.setText("" + porcentaje);
    	rangosPanel.mostrarPorcentajeRangos(porcentaje);
	}

}
